"""Initial schema: 6 tables with relationships and constraints

Revision ID: 7ca5a8ba1aa1
Revises: 
Create Date: 2026-10-08 19:56:24.468666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ca5a8ba1aa1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'COLLECTOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('eco_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('classifications',
    sa.Column('classification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('safety_tips', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('estimated_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('raw_label', sa.String(length=255), nullable=False),
    sa.Column('image_urls', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('classification_id')
    )
    op.create_index(op.f('ix_classifications_category'), 'classifications', ['category'], unique=False)
    op.create_index(op.f('ix_classifications_user_id'), 'classifications', ['user_id'], unique=False)
    op.create_table('collectors',
    sa.Column('collector_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('accepted_categories', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('collector_id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_collectors_location', 'collectors', ['lat', 'lng'], unique=False)
    op.create_table('pickups',
    sa.Column('pickup_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('collector_id', sa.UUID(), nullable=True),
    sa.Column('classification_id', sa.UUID(), nullable=True),
    sa.Column('item_description', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('address_street', sa.String(length=255), nullable=False),
    sa.Column('address_city', sa.String(length=100), nullable=False),
    sa.Column('address_state', sa.String(length=100), nullable=False),
    sa.Column('address_pincode', sa.String(length=20), nullable=False),
    sa.Column('address_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('address_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'IN_TRANSIT', 'COMPLETED', 'CANCELLED', name='pickupstatus'), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.classification_id'], ),
    sa.ForeignKeyConstraint(['collector_id'], ['collectors.collector_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('pickup_id')
    )
    op.create_index(op.f('ix_pickups_collector_id'), 'pickups', ['collector_id'], unique=False)
    op.create_index(op.f('ix_pickups_scheduled_at'), 'pickups', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_pickups_status'), 'pickups', ['status'], unique=False)
    op.create_index(op.f('ix_pickups_user_id'), 'pickups', ['user_id'], unique=False)
    op.create_table('eco_point_transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pickup_id', sa.UUID(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickups.pickup_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('pickup_id')
    )
    op.create_index(op.f('ix_eco_point_transactions_user_id'), 'eco_point_transactions', ['user_id'], unique=False)
    op.create_table('recycler_slots',
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('collector_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('pickup_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('ends_at > starts_at', name='check_slot_time_range'),
    sa.ForeignKeyConstraint(['collector_id'], ['collectors.collector_id'], ),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickups.pickup_id'], ),
    sa.PrimaryKeyConstraint('slot_id'),
    sa.UniqueConstraint('pickup_id')
    )
    op.create_index(op.f('ix_recycler_slots_collector_id'), 'recycler_slots', ['collector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recycler_slots_collector_id'), table_name='recycler_slots')
    op.drop_table('recycler_slots')
    op.drop_index(op.f('ix_eco_point_transactions_user_id'), table_name='eco_point_transactions')
    op.drop_table('eco_point_transactions')
    op.drop_index(op.f('ix_pickups_user_id'), table_name='pickups')
    op.drop_index(op.f('ix_pickups_status'), table_name='pickups')
    op.drop_index(op.f('ix_pickups_scheduled_at'), table_name='pickups')
    op.drop_index(op.f('ix_pickups_collector_id'), table_name='pickups')
    op.drop_table('pickups')
    op.drop_index('idx_collectors_location', table_name='collectors')
    op.drop_table('collectors')
    op.drop_index(op.f('ix_classifications_user_id'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_category'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
